[tool.poetry]
name = "mikrotik-exploit"
version = "0.1.0"
description = "Proof of Concept of RouterOS v6.42 Critical Vulnerability (CVE-2018-14847)"
authors = ["Henrique Sebastião <contato@henriquesebastiao.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
ignr = "^2.2"
isort = "^5.13.2"
ruff = "^0.4.4"
blue = "^0.9.1"
taskipy = "^1.12.2"
radon = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 79

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.lint.per-file-ignores]
"*.py" = ["F403", "E722"]

[tool.taskipy.tasks]
ruff = "ruff check ."
blue = "blue --check . --diff"
isort = "isort --check --diff ."
radon = "radon cc ./bot -a -na"
lint = "task ruff && task blue && task isort"
format = 'blue .  && isort .'
ready = "task lint && task radon"